name = "worker-api-acotizar"
main = "src/index.ts"
compatibility_date = "2026-05-26"

[[d1_databases]]
binding = "DB"
database_name = "acotizar_db"
database_id = "f22ae922-5e7d-4ef9-8282-b6d5cc38f1ae"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "posmin_kv"
